[layout]
orientation = "landscape"
x_scale = "log"
y_scale = "timelog"
y_time_start = 20
y_time_end = 174800
header_height.in = 0.25
header_margin.in = 0.125
header_date_width.in = 1.5
grid_width.in = 7
grid_height.in = 5
grid_major_spacing.in = 1
grid_minor_spacing.in = 0.1
footer_spacing.in = 0.25
